# -*- coding: utf-8 -*-
"""reviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k9N5Drm6h5rNUMJxTONsZpfl5sa0NAgZ
"""

!pip install transformers torch pandas

from transformers import pipeline
import pandas as pd
sentiment = pipeline("sentiment-analysis")
reviews = """the laptop starts quickly and works smooothly for daily tasks.the screen quality is clear and goood for watching videos.
battery backup is average and needs charging often.
the fan makes noise when many apps are running.
overall,it is a good laptop for students but not for gaming.
"""