# -*- coding: utf-8 -*-
"""similarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UzWnJn2QfjToQirEVAEaWjAzklv-lU3v
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util
#load the model
model = SentenceTransformer('all-MiniLM-L6-v2')
text1 = input("Enter text1: ")
text2 = input("Enter text2: ")
#convert text into embeddings
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)
similarity = util.cos_sim(embedding1,embedding2)
print("\nsimilarity score: ",round(float(similarity), 2))
if similarity > 0.75:
  print("similarity Score: high")
elif similarity > 0.4:
  print("similarity Score : mediam")
else:
  print("similarity Score : low")