# -*- coding: utf-8 -*-
"""text generation code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lHbRJXhoh6RaSKRt3RxgZUwHyWPX1AR
"""

!pip install transformers torch

from transformers import pipeline
# load text generation model (GenAI)
generator = pipeline(
    "text-generation",
    model="gpt2"
)
#input format
prompt = "Artificial Intelligence in finance will"
#Generate text
result = generator(prompt,max_length=50,num_return_sequences=1)
print("AI Generated Text:")
print(result[0]['generated_text'])