# -*- coding: utf-8 -*-
"""time table.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14oOutR2g7Y6TTfn4zEe2pXvGYNCpnuE_
"""

!pip install transformers

import pandas as pd
import random
print("TIMETABLE GENERATOR\n")
subjects_input = input("Enter subjects (comma separated): ")
days_input = input("Enter days (comma separated): ")
periods_per_day= int(input("Enter number of periods per day:"))
subjects = [s.strip() for s in subjects_input.split(",") if s.strip()]
days = [d.strip() for d in days_input.split(",") if d.strip()]
if not subjects or not days or periods_per_day <= 0:
   print("Invalid input.please try again.")
else:
  timetable = {}
for day in days:
    timetable[day] = random.choices(subjects, k=periods_per_day)
df = pd.DataFrame(timetable)
df.index = [f"period {i+1}" for i in range(periods_per_day)]
print("\nTimetable Generated Successfully\n ")
display(df)
df.to_csv("timetable.csv")
print("\nTimetable saved as timetable.csv")